service: casasoft-api-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  apiName: casasoft-api
  environment:
    INGREDIENT_TABLE: ${self:custom.ingredientTableName}

custom:
  ingredientTableName: ingredient-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  getIngredientById:
    handler: api.getIngredientById
    name: get-ingredient-by-id
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: ingredient/{ingredientId}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resource: !GetAtt PostsTable.Arn
  createIngredient:
    handler: api.createIngredient
    name: create-ingredient
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: ingredient
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt PostsTable.Arn
  updateIngredientById:
    handler: api.updateIngredientById
    name: update-ingredient-by-id
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: ingredient/{ingredientId}
          method: PUT
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resource: !GetAtt PostsTable.Arn
  deleteIngredientById:
    handler: api.deleteIngredientById
    name: delete-ingredient-by-id
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: ingredient/{ingredientId}
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:DeleteItem"
        Resource: !GetAtt PostsTable.Arn
  findIngredients:
    handler: api.findIngredients
    name: find-ingredients
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: find
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt PostsTable.Arn

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ingredientTableName}
        AttributeDefinitions:
          - AttributeName: ingredientId
            AttributeType: S
        KeySchema:
          - AttributeName: ingredientId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
